version: '3.8'

services:
  upload:
    build:
      context: ./upload-service
    ports:
      - '5000:5000'
    depends_on:
      - kafka

  transcode:
    build:
      context: ./transcoder-service
    ports:
      - '5001:5001'
    depends_on:
      - kafka

  watch:
    build:
      context: ./watch-service
    ports:
      - '5002:5002'
    depends_on:
      - kafka

  # kafka:
  #   image: apache/kafka:3.8.0
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   depends_on:
  #     - zookeeper
  #   volumes:
  #     - kafka-data:/var/lib/kafka/data

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:5.3.0
    container_name: kafka
    environment:
      ## COnfigure listener here like ip:port for external access and localhost:port for host only access
      ## or configure localhost:port1 & ip:port2 together for enabling host as well as external access both
      ## Here Plaintext refers to Protocol for Kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ### For listening to multiple listeners add the name as follows below with different ports for each
      # LISTENER_1://localhost:29092,LISTENER_2://10.138.154.16:9092
      ### Then mention the same in KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181

volumes:
  kafka-data:
